app/src/main/scala/org/alephium/explorer/api/model/Transaction.scala, app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala, app/src/main/scala/org/alephium/explorer/persistence/model/InputEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/model/OutputEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/HashrateQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/CustomTypes.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/InputSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/OutputSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/TransactionSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/UTransactionSchema.scala, app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala, app/src/main/scala/org/alephium/explorer/service/TransactionService.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/service/TokenSupplyServiceSpec.scala, app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala, app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala, benchmark/src/main/scala/org/alephium/explorer/benchmark/db/DBBenchmark.scala, benchmark/src/main/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala, scalastyle-config.xml
Sorry for the long PR.
In this PR  i'm converting our current queries to raw SQL, I kept the previous implementation to validate it returns the same thing (stole the idea from Simer).
Next step/PR will be to introduce the `transaction-by-address` table.
=> Migrate tx queries to raw sql + benchmarking

app/src/main/scala/org/alephium/explorer/persistence/schema/CustomSetParameter.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/QueryUtilSpec.scala
PR for [comment](https://github.com/alephium/explorer-backend/pull/162#discussion_r825413705)
=> Remove `\n` from query placeholders

app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/AppServer.scala, app/src/main/scala/org/alephium/explorer/api/InfosEndpoints.scala, app/src/main/scala/org/alephium/explorer/api/model/GroupIndex.scala, app/src/main/scala/org/alephium/explorer/api/model/PerChainValue.scala, app/src/main/scala/org/alephium/explorer/docs/Documentation.scala, app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala, app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala, app/src/main/scala/org/alephium/explorer/service/BlockService.scala, app/src/main/scala/org/alephium/explorer/service/TransactionService.scala, app/src/main/scala/org/alephium/explorer/web/InfosServer.scala, app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala, app/src/test/scala/org/alephium/explorer/web/InfosServerSpec.scala
=> Add `/infos/total-transactions` and `/infos/average-block-times` endpoints

app/src/main/scala/org/alephium/explorer/persistence/model/InputEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/model/OutputEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/model/TransactionEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/model/TransactionPerAddressEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/BlockDepQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/HashrateQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/InputQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/OutputQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/BlockDepsSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/BlockHeaderSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/HashrateSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/InputSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/LatestBlockSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/OutputSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/TokenSupplySchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/TransactionPerAddressSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/TransactionSchema.scala, app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala, app/src/test/scala/org/alephium/explorer/Generators.scala, app/src/test/scala/org/alephium/explorer/persistence/schema/CustomTypesSpec.scala, benchmark/src/main/scala/org/alephium/explorer/benchmark/db/DataGenerator.scala, benchmark/src/main/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala, benchmark/src/main/scala/org/alephium/explorer/benchmark/db/state/ListBlocksReadState.scala
Thus are reserved SQL key words and we had some issues in the past.
Resolves #157
=> Rename order/index table fields

app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala
=> typo: Addressess -> Addresses

app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/api/InfosEndpoints.scala, app/src/main/scala/org/alephium/explorer/cache/CaffeineAsyncCache.scala, app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala, app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala, app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala, app/src/main/scala/org/alephium/explorer/service/TransactionService.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala, app/src/test/scala/org/alephium/explorer/web/InfosServerSpec.scala
=> Uses `CaffeineAsyncCache` for initialising other caches

app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/api/ChartsEndpoints.scala, app/src/main/scala/org/alephium/explorer/docs/Documentation.scala, app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala
2 minutes is too long for the read-only app.
This is a quick fix related to #186 
An option we can check for later is to have all those timeouts set in
the config file and we can give different value between the read-only
and read-write app.
=> Change block count cache timeout

app/src/test/scala/org/alephium/explorer/ApplicationSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/DatabaseFixture.scala, app/src/test/scala/org/alephium/explorer/persistence/DatabaseFixtureForAll.scala, app/src/test/scala/org/alephium/explorer/persistence/DatabaseFixtureForEach.scala, app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/dao/UnconfirmedTxDaoSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/BlockDepQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/BlockQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/InputQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/OutputQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/schema/CustomJdbcTypesSpec.scala, app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala, app/src/test/scala/org/alephium/explorer/service/HashrateServiceSpec.scala, app/src/test/scala/org/alephium/explorer/service/MempoolSyncServiceSpec.scala, app/src/test/scala/org/alephium/explorer/service/TokenSupplyServiceSpec.scala, app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
=> #146: close test database connections after use

app/src/main/scala/org/alephium/explorer/cache/AsyncReloadingCache.scala, app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala, app/src/main/scala/org/alephium/explorer/service/TransactionService.scala, app/src/main/scala/org/alephium/explorer/web/InfosServer.scala, app/src/test/scala/org/alephium/explorer/cache/AsyncReloadingCacheSpec.scala, app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala, app/src/test/scala/org/alephium/explorer/web/InfosServerSpec.scala
- Towards #200
- Adds `AsyncReloadingCache`.
=> #200: Added `AsyncReloadingCache`

app/src/main/scala/org/alephium/explorer/cache/CaffeineAsyncCache.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/InputQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- Remove redundant fixme
- Remove unused `prefix: String` param from query
- Use `contains` instead of `.get(...).isEmpty`
- Use `forAll` instead of `map(...).getOrElse(true)`
=> Minor things

app/src/main/scala/org/alephium/explorer/persistence/queries/HashrateQueries.scala, app/src/main/scala/org/alephium/explorer/service/HashrateService.scala, app/src/test/scala/org/alephium/explorer/service/HashrateServiceSpec.scala
- Towards issue #201
- Stateless `HashrateQueries`
=> Stateless `HashrateQueries`

app/src/main/scala/org/alephium/explorer/AppServer.scala, app/src/main/scala/org/alephium/explorer/Application.scala, app/src/main/scala/org/alephium/explorer/service/HashrateService.scala, app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala, app/src/main/scala/org/alephium/explorer/util/Scheduler.scala, app/src/main/scala/org/alephium/explorer/web/ChartsServer.scala, app/src/main/scala/org/alephium/explorer/web/InfosServer.scala, app/src/test/scala/org/alephium/explorer/service/HashrateServiceSpec.scala, app/src/test/scala/org/alephium/explorer/service/TokenSupplyServiceSpec.scala, app/src/test/scala/org/alephium/explorer/util/SchedulerSpec.scala, app/src/test/scala/org/alephium/explorer/web/InfosServerSpec.scala
- Towards issue #201
- Stateless `HashrateService` & `TokenSupplyService`
- Both services use the `Scheduler` from #232
=> Stateless `HashrateService` & `TokenSupplyService`

app/src/main/resources/application.conf, app/src/main/scala/org/alephium/explorer/Application.scala, app/src/main/scala/org/alephium/explorer/Main.scala, app/src/test/scala/org/alephium/explorer/ApplicationSpec.scala
=> Add `direct-clique-access` config field

app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala
We'd better read configs with a lib
=> Fix config

app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- #208: remove unused `main_chain` query
- close parens for `toString()`
- remove redundant doc `@param prefix`
=> Minor cleaning

.github/workflows/docker-buildx.yml, build.sbt, docker/release/Dockerfile.release, docker/release/entrypoint.sh
=> Add docker workflow for Apple M1 architecture

README.md
Add quick tutorial for dev who want explorer to reference a full node on another computer within the same subnet.
This is in reference to Discord thread here: https://discord.com/channels/747741246667227157/747998556090269787/998297942211436604
=> node customization readme

app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
=> #192: Fix flaky test `get tx by address`

project/Dependencies.scala
=> Update test libraries

app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala, app/src/test/scala/org/alephium/explorer/GenApiModel.scala, app/src/test/scala/org/alephium/explorer/GenCoreUtil.scala, app/src/test/scala/org/alephium/explorer/GenDBModel.scala, app/src/test/scala/org/alephium/explorer/GenModel.scala, app/src/test/scala/org/alephium/explorer/Generators.scala, app/src/test/scala/org/alephium/explorer/api/model/ApiModelSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/dao/UnconfirmedTxDaoSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/BlockQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/OutputQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala, app/src/test/scala/org/alephium/explorer/service/MempoolSyncServiceSpec.scala, app/src/test/scala/org/alephium/explorer/service/TokenSupplyServiceSpec.scala, app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala, app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
=> Add missing api model serialization test

app/src/main/scala/org/alephium/explorer/util/Scheduler.scala, build.sbt
- Resolves #111
- Renews an old PR #182
=> Resolves #111: enable `inline`

app/src/main/scala/org/alephium/explorer/web/InfosServer.scala
=> Add a cache for token supply

build.sbt
resolves https://github.com/alephium/explorer-backend/issues/324
is it enough for you @simerplaha ?
=> Disable inline logs

app/src/main/scala/org/alephium/explorer/persistence/queries/TokenQueries.scala, app/src/test/scala/org/alephium/explorer/GenDBModel.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/TokenQueriesSpec.scala
raw queries was using a wrongly named column....and there was no test :sweat_smile:
=> Fix token transactions queries

docker/release/Dockerfile.release
This error `at java.io.FileNotFoundException: /nonexistent/.explorer/logs/explorer-info.log (No such file or directory)` appears because no homefolder exists for user nobody
=> Create nobody home folder

app/src/main/scala/org/alephium/explorer/cache/AsyncReloadingCache.scala
- Resolves #372
- Changed `reloadFuture` to return a `Future` the completes only after the newly fetched cache is value is set or if the future fails.
=> fix #372: Return future only after the new cache value is set

app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/api/TransactionEndpoints.scala, app/src/main/scala/org/alephium/explorer/api/UnconfirmedTransactionEndpoints.scala, project/Dependencies.scala
We'll release `1.9.0 `after that
=> Feature/common 1.5.0

app/src/main/scala/org/alephium/explorer/service/SanityChecker.scala
- Resolves #242
- Adds thread-safety to `SanityChecker`
- Failures executing `SanityChecker` are logged
=> #242: Added thread-safety to `SanityChecker`

app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala
I added an error message in case someone forgot to reset their db:
=> Reset migrations

app/src/main/scala/org/alephium/explorer/persistence/model/BlockEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/model/BlockHeader.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/BlockHeaderSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala, app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala, app/src/test/scala/org/alephium/explorer/Generators.scala, app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala, benchmark/src/test/scala/org/alephium/explorer/benchmark/db/DataGenerator.scala, benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala, benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/BlockHeaderMainChainReadState.scala, benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/ListBlocksReadState.scala
Running from scratch is now working as expected :+1:
=> Fix coinbase flag for genesis block and remove `BlockEntry.coinbaseTxId`

app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala, app/src/main/scala/org/alephium/explorer/api/QueryParams.scala, app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/TokenQueries.scala, app/src/main/scala/org/alephium/explorer/service/TransactionService.scala, app/src/main/scala/org/alephium/explorer/web/AddressServer.scala, app/src/test/scala/org/alephium/explorer/service/EmptyTransactionService.scala
=> Add pagination to `/addresses/<address>/tokens` endpoint

app/src/main/resources/grafana/explorer-backend-overview.json
Naming has been changed by tapir.
=> Fix grafana

app/src/main/scala/org/alephium/explorer/persistence/queries/InputQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/OutputQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
related to https://github.com/alephium/explorer-backend/issues/426
=> Use parametric queries instead of spliced values

Makefile
=> Introduce a Makefile

app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala, app/src/main/scala/org/alephium/explorer/persistence/model/InputEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/model/OutputEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/model/TokenOutputEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/OutputSchema.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/TokenOutputSchema.scala, app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala, app/src/main/scala/org/alephium/explorer/service/FinalizerService.scala, app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala, app/src/test/scala/org/alephium/explorer/GenDBModel.scala, app/src/test/scala/org/alephium/explorer/Generators.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala, benchmark/src/test/scala/org/alephium/explorer/benchmark/db/DataGenerator.scala, benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala
As explain in [this issue](https://github.com/alephium/explorer-backend/issues/86)
A Release will need to be done and run over our network before the next one.
=> Spent timestamp

app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala
Otherwise the token supply computation will fail.
Token supply is always computed up to the current day, so as long as the last finalized input is at least in the current day, we are safe.
If you sync from scratch, no migration is run.
I made multiple test locally with mainnet data, when `v1.14.1` hasn't finish the migration, the application fail on start with the correct warning message. Once `spent_timestamp` are up to date, it successfully start and update latest migration to version 4.
This PR is mostly to avoid compatibility problems from external users. Our mainnet backend is already up to date.
=> Add a migration warning to make sure `spent_timestamp` is up to date

app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/api/ContractsEndpoints.scala, app/src/main/scala/org/alephium/explorer/api/QueryParams.scala, app/src/main/scala/org/alephium/explorer/api/Schemas.scala, app/src/test/scala/org/alephium/explorer/web/ContractServerSpec.scala, project/Dependencies.scala
Resolves: #484
This PR is following [this change](https://github.com/alephium/alephium/pull/972) in the node
=> Use better format for path schema

app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala, app/src/main/scala/org/alephium/explorer/api/TokensEndpoints.scala, app/src/main/scala/org/alephium/explorer/api/model/FungibleTokenMetadata.scala, app/src/main/scala/org/alephium/explorer/api/model/NFTMetadata.scala, app/src/main/scala/org/alephium/explorer/api/model/StdInterfaceId.scala, app/src/main/scala/org/alephium/explorer/docs/Documentation.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/TokenQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala, app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/TokenQueriesSpec.scala
As discussed on our slack explorer channel
cc @nop33
=> Token metadata fixes

app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala, app/src/main/scala/org/alephium/explorer/api/BaseEndpoint.scala, app/src/main/scala/org/alephium/explorer/api/EndpointExamples.scala, app/src/main/scala/org/alephium/explorer/api/TokensEndpoints.scala, app/src/main/scala/org/alephium/explorer/docs/Documentation.scala, app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala
As discussed @polarker 
There was already the max items info, but it was a bit hidden in the schema tab
So I added a description
=> Open api improvement

app/src/main/resources/application.conf, app/src/test/scala/org/alephium/explorer/service/MarketServiceSpec.scala
Resolves: https://github.com/alephium/explorer-backend/issues/514
=> Add CAD currency

app/src/main/resources/application.conf
Resolves: https://github.com/alephium/explorer-backend/issues/523
=> Disable `direct-clique-access` by default

app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala, app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala, app/src/main/scala/org/alephium/explorer/persistence/model/ContractEntity.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/ContractQueries.scala, app/src/test/scala/org/alephium/explorer/ConfigDefaults.scala, app/src/test/scala/org/alephium/explorer/GenCoreApi.scala, app/src/test/scala/org/alephium/explorer/persistence/model/ContractEntitySpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/ContractQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/service/EmptyBlockFlowClient.scala, app/src/test/scala/org/alephium/explorer/service/EmptyTransactionService.scala, project/Dependencies.scala
The new release after the merge will need a full re-sync to handle the new event  change.
=> Update to node `2.11.0`

README.md, app/src/main/scala/org/alephium/explorer/Main.scala, app/src/main/scala/org/alephium/explorer/WelcomeMessage.scala, app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala, app/src/main/scala/org/alephium/explorer/config/Platform.scala, app/src/main/scala/org/alephium/explorer/error/ExplorerError.scala, app/src/main/scala/org/alephium/explorer/util/FileUtil.scala
I also took the opportunity to add more info when starting the app
=> Configuration also via `user.conf` file

app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala, app/src/main/scala/org/alephium/explorer/service/FinalizerService.scala, app/src/test/scala/org/alephium/explorer/service/FinalizerServiceSpec.scala
This PR addresses a concurrency issue in the `FinalizerService` that occurs during the finalization process while syncing  from scratch.
When finalizing, we check the latest inserted input and compare its timestamp with the finalization threshold (`~(now - 1 hour)`). Inputs older than this threshold are finalized, and the app_state table is updated to reflect the finalization up to this point.
In a fully synced explorer-backend, the latest input is typically newer than the finalization timestamp, allowing the process to complete without issue.
However, when syncing from scratch, we encounter a concurrency issue. Blocks are fetched in timestamp batches from the node, with 16 lists of blocks (one per chain) processed in parallel.
The problem arises when a block from one chain (e.g., (0,0)) …
=> Fix concurrency issue in `Finalizer service`

app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala, app/src/main/scala/org/alephium/explorer/api/EndpointExamples.scala, app/src/main/scala/org/alephium/explorer/api/QueryParams.scala, app/src/main/scala/org/alephium/explorer/api/model/Pagination.scala, app/src/main/scala/org/alephium/explorer/api/model/TransactionInfo.scala, app/src/main/scala/org/alephium/explorer/docs/Documentation.scala, app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala, app/src/main/scala/org/alephium/explorer/service/TransactionService.scala, app/src/main/scala/org/alephium/explorer/web/AddressServer.scala, app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala, app/src/test/scala/org/alephium/explorer/service/EmptyTransactionService.scala, app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala, app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
* Reduce max page limit to 20 and default to 10
* Add /addresses/<address>/latest-transaction endpoint
=> Latest tx info

app/src/main/scala/org/alephium/explorer/ExploreHttpServer.scala, app/src/main/scala/org/alephium/explorer/ExplorerState.scala, app/src/main/scala/org/alephium/explorer/cache/BlockCache.scala, app/src/main/scala/org/alephium/explorer/cache/MetricCache.scala, app/src/main/scala/org/alephium/explorer/cache/TransactionCache.scala, app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala, app/src/main/scala/org/alephium/explorer/persistence/model/LatestBlock.scala, app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala, app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala, app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala, app/src/main/scala/org/alephium/explorer/service/HashrateService.scala, app/src/main/scala/org/alephium/explorer/service/HolderService.scala, app/src/main/scala/org/alephium/explorer/service/MempoolSyncService.scala, app/src/main/scala/org/alephium/explorer/service/TokenService.scala, app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala, app/src/main/scala/org/alephium/explorer/util/Scheduler.scala, app/src/main/scala/org/alephium/explorer/util/TimeUtil.scala, app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala, app/src/test/scala/org/alephium/explorer/persistence/queries/BlockQueriesSpec.scala, app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala, app/src/test/scala/org/alephium/explorer/util/TimeUtilSpec.scala
This PR includes several updates to improve syncing performance + boot up speed
* Reduced unnecessary node calls and improved syncing using BlockCache.
* Eliminated startup delays by removing wait-on-boot tasks and deferring cache loading.
* Ensured incorrect interface IDs are stored in the database to prevent repeated updates.
* Reduced log noise in multiple services and removed unused queries.
*  Ensured the database initializes before the HTTP server to avoid timeouts.
*  Improved ExplorerState to ensure proper service handling.
=> Improve sycing and boot speed.

app/src/main/resources/application.conf, app/src/main/resources/explorer-backend-openapi.json, app/src/main/scala/org/alephium/explorer/AppServer.scala, app/src/main/scala/org/alephium/explorer/ExplorerState.scala, app/src/main/scala/org/alephium/explorer/api/EndpointExamples.scala, app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala, app/src/main/scala/org/alephium/explorer/docs/Documentation.scala, app/src/main/scala/org/alephium/explorer/service/MarketService.scala, app/src/main/scala/org/alephium/explorer/web/DocumentationServer.scala, app/src/main/scala/org/alephium/explorer/web/MarketServer.scala, app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala, app/src/test/scala/org/alephium/explorer/service/MarketServiceSpec.scala, tools/src/main/scala/org/alephium/tools/OpenApiUpdate.scala
resolves https://github.com/alephium/explorer-backend/issues/557
Thx to Mobula, we can now find the price for almost all our token list, only ~40 tokens don't have a price.
In this PR we are now taking the token list and grab the price for all of them from mobula.
As previously we cache the data and reload every 5min.
=> Mobula integration

app/src/main/resources/application.conf, app/src/main/scala/org/alephium/explorer/api/EndpointExamples.scala, app/src/main/scala/org/alephium/explorer/api/model/Price.scala, app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala, app/src/main/scala/org/alephium/explorer/service/MarketService.scala, app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala, app/src/test/scala/org/alephium/explorer/service/MarketServiceSpec.scala
When liquidity it to low, prices can be totally wrong.
=> Set a minimum liquidity for tokens

app/src/main/resources/application.conf, app/src/main/scala/org/alephium/explorer/ExplorerState.scala, app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala, app/src/main/scala/org/alephium/explorer/service/MarketService.scala, app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala, app/src/test/scala/org/alephium/explorer/GenCoreApi.scala, app/src/test/scala/org/alephium/explorer/service/MarketServiceSpec.scala
API key is optional, but if none is provided, the market service will return error when getting price.
=> Add API for mobula

app/src/main/resources/application-mainnet.conf, app/src/main/resources/application-testnet.conf, app/src/test/scala/org/alephium/explorer/config/ExplorerConfigSpec.scala
Migration will come in another PR
=> Fix danube conf to compute hashrate
