- README.md
- build.sbt
For some reasons, running `sbt app/run` is all fine, but without this
commit, `java -jar` is throwing a null pointer exception.
Found by @nop33
> Fix release jar

- app/src/main/scala/org/alephium/explorer/cache/CaffeineAsyncCache.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/service/BlockService.scala
- app/src/test/scala/org/alephium/explorer/Generators.scala
- app/src/test/scala/org/alephium/explorer/cache/CaffeineAsyncCacheSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
- benchmark/src/main/scala/org/alephium/explorer/benchmark/db/DBBenchmark.scala
- build.sbt
- Added a cache `cacheRowCount: CaffeineAsyncCache[Query[_, _, Seq], Int]` which will cache any `count` query. This PR uses it for `listMainChain` only.
- Added a wrapper `CaffeineAsyncCache` to centralise handling Caffeine's Java to Scala type conversions. 
- Resolves #119
The following benchmark shows around 20% performance improvement. 
#156 will remove deprecated apis `listMainChain` and `listMainChainSQL` with `listMainChainSQLCached`.
> Cached `main_chain` count query

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala
- app/src/main/scala/org/alephium/explorer/api/model/AddressBalance.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
The idea is for the front-end to call those two endpoints rather than
the one to get all info at once.
With this we could show the address details faster and also the
transactions pagination.
> Add `/address/total-transaction` and `/address/balance` endpoint

- app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/UnconfirmedTxDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/HashrateQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/InputQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/OutputQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/BlockDepsSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/BlockHeaderSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomJdbcTypes.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomTypes.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/HashrateSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/InputSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/LatestBlockSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/OutputSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/Schema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TokenSupplySchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TransactionPerAddressSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TransactionSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/UInputSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/UOutputSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/UTransactionSchema.scala
- app/src/main/scala/org/alephium/explorer/service/HashrateService.scala
- app/src/main/scala/org/alephium/explorer/service/SanityChecker.scala
- app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/UnconfirmedTxDaoSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/schema/CustomJdbcTypesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/schema/CustomTypesSpec.scala
- Adds to PR #163
- Moved Slick's `GetResult` types from `trait CustomTypes` to `object CustomGetResult`
- Updated & renamed `trait CustomTypes` to `object CustomJdbcTypes`
> Updated `trait`s to be plain `object`s

- app/src/main/scala/org/alephium/explorer/Application.scala
- app/src/main/scala/org/alephium/explorer/Main.scala
- app/src/main/scala/org/alephium/explorer/persistence/DBInitializer.scala
- app/src/main/scala/org/alephium/explorer/persistence/DBRunner.scala
- app/src/test/scala/org/alephium/explorer/ApplicationSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/DatabaseFixture.scala
- app/src/test/scala/org/alephium/explorer/persistence/DatabaseFixtureForAll.scala
- app/src/test/scala/org/alephium/explorer/persistence/DatabaseFixtureForEach.scala
- benchmark/src/main/scala/org/alephium/explorer/benchmark/db/state/BlockEntityWriteState.scala
- First PR for a series of other PRs working towards #201
- Updates `DBInitializer` to be stateless
The issue #201 can be implemented framework-less if majority of the code is made stateless. Previously statefulness was required because of H2 dependency, that got resolved by Thomas in #163. 
Being simple objects a plain function our services would be just a function (`syncOnce`) that's executed periodically by a `Scheduler` (implemented in one of the commits in the screenshot) making the code much simpler.
The following types are the only global parameters required by 90% of the code and there is no mutation.
- `ExecutionContext` 
- `DatabaseConfig[PostgresProfile]`
- `GroupConfig` (for some)
Mutation occurs only in caches which is encapsulated and managed in a dedicated class.
I've got …
> Updated `DBInitializer` to be stateless

- app/src/main/scala/org/alephium/explorer/Application.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/HealthCheckDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/UnconfirmedTxDao.scala
- app/src/main/scala/org/alephium/explorer/service/MempoolSyncService.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/UnconfirmedTxDaoSpec.scala
- app/src/test/scala/org/alephium/explorer/service/MempoolSyncServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
- Second PR towards issue #201
- Updated `UnconfirmedTxDao` & `HealthCheckDao` to be stateless
- Build on top of PR #227
> Stateless `UnconfirmedTxDao` & `HealthCheckDao`

- app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/service/SanityChecker.scala
- app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/BlockQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
- benchmark/src/main/scala/org/alephium/explorer/benchmark/db/DBBenchmark.scala
- benchmark/src/main/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala
- Third PR towards issue #201
- Updated `BlockQueries` & `TransactionQueries` to be stateless
> Stateless `BlockQueries` & `TransactionQueries`

- app/src/main/resources/application.conf
- app/src/main/scala/org/alephium/explorer/AppServer.scala
- app/src/main/scala/org/alephium/explorer/Application.scala
- app/src/main/scala/org/alephium/explorer/Main.scala
- app/src/main/scala/org/alephium/explorer/cache/TransactionCache.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/main/scala/org/alephium/explorer/web/BlockServer.scala
- app/src/main/scala/org/alephium/explorer/web/ChartsServer.scala
- app/src/main/scala/org/alephium/explorer/web/DocumentationServer.scala
- app/src/main/scala/org/alephium/explorer/web/InfosServer.scala
- app/src/main/scala/org/alephium/explorer/web/TransactionServer.scala
- app/src/main/scala/org/alephium/explorer/web/UtilsServer.scala
- app/src/test/scala/org/alephium/explorer/ApplicationSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
- app/src/test/scala/org/alephium/explorer/web/InfosServerSpec.scala
- benchmark/src/main/scala/org/alephium/explorer/benchmark/db/DBBenchmark.scala
- benchmark/src/main/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala
- Towards #201
- Stateless `TransactionService` & `TransactionDao`
- remove unused parameter `blockflowFetchMaxAge`
> Stateless `TransactionService` & `TransactionDao`

- app/src/main/scala/org/alephium/explorer/AppServer.scala
- app/src/main/scala/org/alephium/explorer/Application.scala
- app/src/main/scala/org/alephium/explorer/service/SanityChecker.scala
- app/src/main/scala/org/alephium/explorer/web/UtilsServer.scala
- Towards #201
- Stacked PR of previous un-merged PR #240
- Stateless `SanityChecker`
`SanityChecker` has mutable vars `running`, `i`, `totalNbOfBlocks` which from a quick look can be removed and implemented immutably. Is this something we want done?
Two more left - `BlockFlowSyncService` and `MempoolSyncService`.
> Stateless `SanityChecker`

- app/src/main/scala/org/alephium/explorer/Application.scala
- app/src/main/scala/org/alephium/explorer/util/FutureUtil.scala
Quick fix #249. Blocking-ly Initialises database first on `Application` boot-up before the cache is initialised. 
Or we can wait for a proper fix when #201 gets resolved with updates to `Application.scala` & `Main.scala`?
> #249: Initialise database first

- app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/InputQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/OutputQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
- app/src/test/scala/org/alephium/explorer/web/InfosServerSpec.scala
- benchmark/src/main/scala/org/alephium/explorer/benchmark/db/DBBenchmark.scala
We kept lots of functions that were written in `slick` just to validate
that the new corresponding SQL functions were correct.
I think we ran everything in prod for long enough to validate it's correct.
This was also getting annoying to maintain as soon as we are adding a column somewhere.
> Remove unused and duplicate function in various places

- app/src/main/scala/org/alephium/explorer/persistence/DBInitializer.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/AppStateSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/BlockHeaderSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/OutputSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/SchemaMainChain.scala
- benchmark/src/main/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala
- benchmark/src/main/scala/org/alephium/explorer/benchmark/db/state/ListBlocksReadState.scala
- Removed `AppStateSchema` extending `SchemaMainChain` because it does not create `main_chain` column or index. 
- #210: Removed `lazy val` from `create*Index` because they are not concurrently initialised or need to be kept alive throughout the application. Should be discarded by GC after DB is initialised.
> #210: Remove `lazy val` 

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/Schemas.scala
- app/src/main/scala/org/alephium/explorer/api/UtilsEndpoints.scala
- app/src/main/scala/org/alephium/explorer/api/model/LogbackValue.scala
- app/src/main/scala/org/alephium/explorer/docs/Documentation.scala
- app/src/main/scala/org/alephium/explorer/web/UtilsServer.scala
- app/src/test/scala/org/alephium/explorer/web/UtilsServerSpec.scala
Resolves: #196
`update-global-loglevel` takes a single string to update our global log
level (e.g: DEBUG)
`update-log-config` takes a full `logback.xml` file
> Add two endpoints to manage log level

- app/src/main/scala/org/alephium/explorer/persistence/schema/BlockDepsSchema.scala
#283: Removes `deps_hash_idx` from table `block_deps`, already indexed in primary key index `hash_deps_pk`.
> #283: Remove unneeded index `deps_hash_idx`

- app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/package.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/InputQueries.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala
- app/src/test/scala/org/alephium/explorer/GenModel.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
- #206 - Updated `BlockDao.updateInputs` to be transactional.
- Added test-cases for above.
- Updated query `insertTxPerAddressFromInput` to use primary key constraint `txs_per_address_pk`.
> #206: Transactional `BlockDao.updateInputs`

- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockDepQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/BlockQueriesSpec.scala
- Removed splicing from `getBlockHeaderAction` to favour prepared-statements.
- Added test-cases for above.
- fix typo: ingored => ignored.
- Moved `blockDepsQuery` from `BlockQueries` to `BlockDepQueries` and renamed it to `getDepsForBlock`.
> Prepared-statement `getBlockHeaderAction`

- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/BlockQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/util/SlickTestUtil.scala
For issues #208, #123, [comment](https://github.com/alephium/explorer-backend/issues/283#issuecomment-1173800115) and other 'double check' tasks we can write test-cases using `explain()` to assert output of `EXPLAIN ANALYSE` for Slick queries. 
For example:
```scala
val explainQuery = BlockQueries.someQuery(params).explain()
run(explainQuery) should include("Some text from `EXPLAIN ANALYSE` output")
```
I've added an example test for a query in `BlockQueriesSpec` to assert the query uses this `main_chain` index
```sql
index block_headers_full_index
on block_headers (main_chain asc, block_timestamp desc, hash asc, chain_from asc, chain_to asc, height asc);
```
We ok writing such test-cases?
> Added `SlickTestUtil.explain()`: For testing Postgres's `EXPLAIN ANALYSE` output

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala
- app/src/main/scala/org/alephium/explorer/docs/Documentation.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/main/scala/org/alephium/explorer/web/DocumentationServer.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
- app/src/test/scala/org/alephium/explorer/web/InfosServerSpec.scala
- tools/src/main/scala/org/alephium/tools/OpenApiUpdate.scala
based on [this discussion](https://github.com/alephium/desktop-wallet/issues/136#issuecomment-1176264853)
This is a feature needed for address discovery in the desktop-wallet
here is the curl time in second: 
The query is: 
```
SELECT EXISTS (SELECT 1 FROM transaction_per_addresses WHERE address = $address)
```
it's the fastest thing I could find and the one that pop up the more often in all my searches
> Add a super fast endpoint to check if an address is active (at least 1 tx)

- app/src/test/scala/org/alephium/explorer/persistence/queries/BlockQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/InputQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/OutputQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
Ignore index check test-cases until #292 is resolved because the builds are failing often for other PRs. Eg: [log](https://github.com/alephium/explorer-backend/runs/7513711090?check_suite_focus=true#step:5:303)
> Temporarily ignore index check test-cases

- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/ExplainResult.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/OutputQueries.scala
- app/src/main/scala/org/alephium/explorer/service/IndexChecker.scala
- app/src/main/scala/org/alephium/explorer/util/SlickExplainUtil.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/InputQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/OutputQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
- For #283, #191
- Added check for query `getTxnHash` to `IndexChecker`
- Added field `message` to `ExplainResult` for showing more info. For example: The following image shows the output for all indexes used by the query. 
- First is for an `output` with oldest `timestamp`.
- First is for an `output` with latest `timestamp`. 
- Real data used by running sync partially. `173651` rows in `outputs` table, all with `main_chain = true`.
> Added `explain` for query `getTxnHashSQL`

- app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala
- app/src/main/scala/org/alephium/explorer/persistence/model/AppState.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/AppStateQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomJdbcTypes.scala
- app/src/main/scala/org/alephium/explorer/service/FinalizerService.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/AppStateQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/service/FinalizerServiceSpec.scala
- fixes #293
- added `AppStateQueries` and moved calls directly to the table to use `AppStateQueries`.
> fixes #293: Typed `AppStateSchema`

- app/src/main/scala/org/alephium/explorer/persistence/model/BlockHeader.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala
- app/src/main/scala/org/alephium/explorer/util/SlickUtil.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/BlockQueriesSpec.scala
- Resolves #328. 
- Ran the test-case in this PR over 100s of iterations. The test also checks for same output as existing code. So it should cover all existing cases. 
Started off with typed query [here](https://github.com/alephium/explorer-backend/blob/328_getLocalMaxTimestamp_2/app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala#L342) hoping to reuse existing queries to speed things up. But the generated `UNION` queries looked like following so switched to SQL. 
- Remove deprecated code. See TODO in code. 
- Benchmarks. Please let me if you'd like this done.
<details>
<summary>Generated query</summary>
```sql
(select x2.x3 as x4, x2.x5 as x6
from ((select x7.x8 as x3, x7.x9 as x5
from ((select x10.x11 as x8, x10.x12 as x9
from ((select x13.x14 as x11, …
```
> #328: Query for `getLocalMaxTimestamp`

- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala
- app/src/test/scala/org/alephium/explorer/Generators.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/BlockQueriesSpec.scala
- Resolves #333
- This is PR is stacked on #332 (needed the functions implemented there).
[`BlockFlowSyncService.init()`](https://github.com/alephium/explorer-backend/blob/master/app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala#L151) has no existing unit tests. So can't really compare the function's output against this change.  
Please let me know if you'd like test-cases for `BlockFlowSyncService.init()` implemented.
> #333: Fetch data required by `BlockFlowSyncService.init()` in single query

- app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala
Next release `v1.8.0` requires to drop the database and restart from
scratch.
We can thus reset the migrations.
> Reset migration

- app/src/test/scala/org/alephium/explorer/util/SchedulerSpec.scala
- Resolves #335
- The test was failing for timezone `America/Santiago`, it went in daylight saving recently ( -3 hours) making the test-case invalid. I've restricted that test to run for only known timezones (Sydney, Switzerland) so its more predictable.
- Also added more seconds to other test-cases, just incase the build is slow.
> #335: Fix daylight savings test issue

- app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala
`fetchLocalTs` and `fetchRemoteTs` are not conditional and are always executed. Updated `fetchAndBuildTimeStampRange` to be a pure function. 
Replaced the following 
```scala
def fetchAndBuildTimeStampRange(
step: Duration,
backStep: Duration,
fetchLocalTs:  => Future[Option[(TimeStamp, Int)]],
fetchRemoteTs: => Future[Option[(TimeStamp, Int)]]
)
```
with 
```scala
def fetchAndBuildTimeStampRange(
step: Duration,
backStep: Duration,
localTs: Option[(TimeStamp, Int)],
remoteTs: Option[(TimeStamp, Int)]
)
```
[This test case](https://github.com/alephium/explorer-backend/blob/master/app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala#L50) does not perform any IO operation but is creating a database connection and dropping/creating tables because the class extends …
> Replace delayed `Future` execution

- app/src/main/scala/org/alephium/explorer/error/ExplorerError.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/BlockQueriesSpec.scala
- Implements [this comment](https://github.com/alephium/explorer-backend/issues/328#issuecomment-1225295656) to reduce the amount of data read (inputs, outputs, transactions etc) when fetching `parent`.
- Replaced `assert(block.chainFrom == parentBlock.chainFrom && block.chainTo == parentBlock.chainTo)` with error `BlocksInDifferentChains` for better log message incase of error. 
It seems issue #358 is invalid after this because the full block is not being read anymore? Should it be closed?
> Replaced `BlockDao.get(parent)` with `BlockQueries.getBlockChainInfo(parent)`

- app/src/main/scala/org/alephium/explorer/error/ExplorerError.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala
- app/src/main/scala/org/alephium/explorer/util/TimeUtil.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/util/TimeUtilSpec.scala
- Resolves #364
- Splits `fetchAndBuildTimeStampRange()` into smaller functions. 
- Implemented existing test-case using ScalaCheck for coverage and added few more covering failure scenarios.
- Moved existing test-cases without [these abbreviated functions `t` `s` `r`, `th`](https://github.com/alephium/explorer-backend/blob/64495d3f72cd804804c1a9f5e1a75d115c81c230/app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala#L54). Seem more readable without ‘em. But please let me know if you’d like them used anyway.
> #364: Moved `fetchAndBuildTimeStampRange` to `TimeUtil`

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala
- app/src/main/scala/org/alephium/explorer/api/QueryParams.scala
- app/src/main/scala/org/alephium/explorer/api/model/Pagination.scala
- app/src/main/scala/org/alephium/explorer/docs/Documentation.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/test/scala/org/alephium/explorer/GenDBModel.scala
- app/src/test/scala/org/alephium/explorer/TestQueries.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/service/EmptyTransactionService.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/DBBenchmark.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/TransactionsPerAddressReadState.scala
- First version for #375
- Pagination was required so backend does not allow large limits to go through. `100000` being the max limit. Defaults to `20` just like other APIs (Uses existing pagination code). 
- Added `TestQueries` for issue #368. Didn't seem like it was nice to add queries like `clearTable()` to production code. Will update that issue's description if you ok with this.
- Is there a tool that generates `explorer-backend-openapi.json`? Updated this one here by hand.
`/addresses/[address]/timeranged-transactions?fromTs=x&toTs=y`
OR
`/addresses/[address]/timeranged-transactions?fromTs=x&toTs=y&limit=100000`
OR 
`/addresses/[address]/timeranged-transactions?fromTs=x&toTs=y&limit=100000&page=1`
> #375: Time ranged transactions

- app/src/main/resources/application.conf
- app/src/main/scala/org/alephium/explorer/ExplorerState.scala
- app/src/main/scala/org/alephium/explorer/Main.scala
- app/src/main/scala/org/alephium/explorer/SyncServices.scala
- app/src/main/scala/org/alephium/explorer/config/BootMode.scala
- app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala
- app/src/main/scala/org/alephium/explorer/error/ExplorerError.scala
- app/src/main/scala/org/alephium/explorer/persistence/Database.scala
- app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala
- app/src/test/scala/org/alephium/explorer/config/BootModeSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/DatabaseSpec.scala
- app/src/test/scala/org/alephium/explorer/web/InfosServerSpec.scala
- app/src/test/scala/org/alephium/explorer/web/UtilsServerSpec.scala
- Resolves #337
- Added `WriteOnly` (or `SyncOnly` mode). Named it `WriteOnly` to follow the existing naming convention. 
- Uses `ExecutionContext.Implicits.global` for `WriteOnly` mode since `ActorSystem` is not available.
```properties
boot-mode = WriteOnly
```
> #337: Implements `WriteOnly`/`SyncOnly` mode

- app/src/main/scala/org/alephium/explorer/cache/AsyncReloadingCache.scala
- app/src/test/scala/org/alephium/explorer/cache/AsyncReloadingCacheSpec.scala
- Resolves #383
- PR #373 didn't fully resolve the issue. This PR does. It sets the next state of the cache in `Future` itself (`setFree()`) instead of setting it in `onComplete`.
> #383: Fix test-case `expireAndReload immediately`

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala
- app/src/main/scala/org/alephium/explorer/docs/Documentation.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/service/EmptyTransactionService.scala
- app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
- Resolves #299
- Following `areAddressesActive` this endpoint is also a `POST` request. 
- Endpoint: `/addresses/transactions`
- Requires an array of addresses as JSON body `["address1", "address2"]`
> #299: Endpoint to fetch transactions for a list of addresses

- app/src/main/scala/org/alephium/explorer/cache/BlockCache.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
- First PR for #386
- As you mentioned in the issue, the cache is the problem. Cache timeout being 10.second caused delayed test completion. This reduces cache timeout to `1.second` for test-cases. 
- Rough benchmarks
- Test that took 1 minute 21 seconds now finishes in 22 seconds
- Test that took 3 minutes 2 seconds now finishes in 43 seconds
- Out of the 43 seconds, roughly 30 second are used by data generation `genBlockEntityWithOptionalParent()`
If you are ok with this change, will replicate it for other caches and test-cases accessing `BlockCache`.
> #386: Configure low cache timeout for test-cases

- app/src/main/resources/application.conf
- app/src/main/scala/org/alephium/explorer/ExplorerState.scala
- app/src/main/scala/org/alephium/explorer/cache/BlockCache.scala
- app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala
- app/src/test/scala/org/alephium/explorer/cache/TestBlockCache.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/service/TokenSupplyServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/web/InfosServerSpec.scala
- app/src/test/scala/org/alephium/explorer/web/UtilsServerSpec.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/BlockEntityWriteState.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/ListBlocksReadState.scala
- Implements [comment](https://github.com/alephium/explorer-backend/pull/390#discussion_r1026097268)
- Moved `BlockCache` time reload periods to `application.conf`
- For test-cases added `TestBlockCache` instead of a config file.
- Resolves #386
> #386: Move cache time period configuration to `application.conf`

- app/src/main/scala/org/alephium/explorer/cache/BlockCache.scala
Calls to `BlockCache.getAllLatestBlocks` throw the following `NoSuchElementException` when the cache is empty or partially populated.
> java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:627)
at scala.None$.get(Option.scala:626)
at org.alephium.explorer.cache.BlockCache$.$anonfun$apply$2(BlockCache.scala:69)
This PR removes [this](https://github.com/alephium/explorer-backend/blob/09b30e9e7be13dd737da6036ac67fd56b7ee871e/app/src/main/scala/org/alephium/explorer/cache/BlockCache.scala#L69) call to `Option.get`.
> Fix `java.util.NoSuchElementException: None.get`

- app/src/main/resources/logback.xml
- app/src/test/resources/logback-test.xml
We were not configuring the log level at the right place, the threshold is a fixed limit that cannot be passed, it makes sense for the various `FileAppender`, but not for console (in our case).
Resolves: https://github.com/alephium/explorer-backend/issues/391
Calling the update-log-level endpoint now works as expected, I manually tested it.
I tried to add a Unit test, but using mocking is a nightmare and nothing is working or it's ugly as hell.
@polarker let me know if you want me  to do the same in the full node.
> Fix console logging level

- app/src/main/scala/org/alephium/explorer/Main.scala
- app/src/main/scala/org/alephium/explorer/SyncServices.scala
- app/src/main/scala/org/alephium/explorer/error/ExplorerError.scala
- app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala
- app/src/main/scala/org/alephium/explorer/persistence/model/AppState.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/AppStateQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/AppStateSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomJdbcTypes.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala
- app/src/main/scala/org/alephium/explorer/service/FinalizerService.scala
- app/src/main/scala/org/alephium/explorer/util/ExecutionContextUtil.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/AppStateQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/service/EmptyBlockFlowClient.scala
- app/src/test/scala/org/alephium/explorer/util/ExecutionContextUtilSpec.scala
- app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
Resolves #395 and #246 
I took the opportunity to tackle the second as it's related.
`ExecutionContext.reportFailure` is now used to warn the top of the application of a failure, currently we stop the app on all event (we use `reportFailure` only once), but later we could choose to have different kind of behavior.
Now that `SyncServices` can warn and stop the app, I could remove the `sys.exit` from `BlockFlowSyncService`, just need to fail the future and it will be catch by `SyncServices` and trigger the `reportFailure`.
The latest `sys.exit` was in migration, but it was actually a dead branch that couldn't be reach.
following the code, `AppStateQuery.get(MigrationVersion)` couldn't return anything else than `None` or `Some(MigrationVersion(x))`, but from the compiler side, it thought it …
> ExecutionContext.reportFailure and remove all `sys.exit`

- app/src/main/scala/org/alephium/explorer/persistence/DBInitializer.scala
- app/src/test/scala/org/alephium/explorer/persistence/DatabaseFixture.scala
- app/src/test/scala/org/alephium/explorer/persistence/DatabaseFixtureForAll.scala
- app/src/test/scala/org/alephium/explorer/persistence/DatabaseFixtureForEach.scala
Performance are improved a bit  and it seems to make more sense like this, rather than re-creating tables and index every time.
> Clean tables rather than drop/re-create them in `DatabaseFixtureForEach`

- app/src/main/scala/org/alephium/explorer/ExplorerState.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowClientSpec.scala
resolves: #398 
I checked other part of the codes to see if we need to also apply this patter, but it seems not.
> Respect `direct-clique-access` flag in `BlockFlowClient`

- app/src/main/scala/org/alephium/explorer/SyncServices.scala
- app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala
- app/src/main/scala/org/alephium/explorer/service/FinalizerService.scala
- app/src/main/scala/org/alephium/explorer/util/TimeUtil.scala
- app/src/test/scala/org/alephium/explorer/util/TimeUtilSpec.scala
[TimeUtil.buildTimeStampRange](https://github.com/alephium/explorer-backend/blob/de891687eaa0fb11b1002bd61b49e77b41c90a90/app/src/main/scala/org/alephium/explorer/util/TimeUtil.scala#L52-L73): From this function, [it implies that our queries have to be inclusive](https://github.com/alephium/explorer-backend/blob/de891687eaa0fb11b1002bd61b49e77b41c90a90/app/src/test/scala/org/alephium/explorer/util/TimeUtilSpec.scala#L81-L82) on both `fromTs` and `toTs`: if our time ranges are: `(0,2), (3,5)`, if our query has `< toTs`, the first range will take only `0 -> 1` timestamps. On the second range it will take `3 -> 4`, So `2` and `5` will be ignored. We were also handling the case where the last time range was supposed to be exactly the same value, we were adding `+1ms` (see …
> Fix missing finalized outputs

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/BlockEndpoints.scala
- app/src/main/scala/org/alephium/explorer/api/EndpointExamples.scala
- Towards #253.
- Added `Example`s for `BlockEndpoints`.
- Everything is declared as `val` in `EndpointExamples` following the node. Assuming that's preferred.
> #253: OpenAPI `Endpoint` examples for Block APIs

- app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala
- app/src/main/scala/org/alephium/explorer/util/InputAddressUtil.scala
- app/src/test/scala/org/alephium/explorer/util/InputAddressUtilSpec.scala
- project/Dependencies.scala
The  idea is to convert directly the protocol inputs as soon as we access them (only twice in the code) to be sure we have the correct unlock scripts latter.
> Convert `UnlockScript.SameAsPrevious` to the correct value + Bump common to 1.6.x

- app/src/main/scala/org/alephium/explorer/persistence/DBInitializer.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CommonIndex.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TokenTxPerAddressSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TransactionPerAddressSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TransactionPerTokenSchema.scala
Towards #413.
Is there a need to maintain the index names as before?
- Table named `token_tx_per_addresses` has indexes prefixed as `token_tx_per_address_*`
- Table named `transaction_per_addresses` has indexes prefixed as `txs_per_address_*`
This PR use the same prefix as table name.
> #413: multi-column timestamp indexes

- app/src/test/scala/org/alephium/explorer/GenCommon.scala
- app/src/test/scala/org/alephium/explorer/Generators.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/UInputQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/UOutputQueriesSpec.scala
Test cases for tables `uinputs` and `uoutputs`.
| Package: `org.alephium.explorer.persistence.queries` | Class | Method | Line |
|------------------------------------------------------|----------------|-----------------|---------------|
| Initial  coverage                                         | 72% (29/40)    | 59% (203/343)  | 67% (640/950) | 
| Updated coverage 1                                  | 77% (31/40)    | 61% (212/343)   | 70% (665/950) | 
| Updated coverage 2 (this PR)                  | 82% (33/40)   | 66% (228/343)  | 74% (704/950) | 
`UnconfirmedTransactionQueries` coverage  = `100%`.
> Coverage 2: `UInputQueriesSpec` & `UOutputQueriesSpec`

- app/src/main/resources/application.conf
- app/src/main/scala/org/alephium/explorer/AppServer.scala
- app/src/main/scala/org/alephium/explorer/ExplorerState.scala
- app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/test/scala/org/alephium/explorer/service/EmptyTransactionService.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
- docker/release/Dockerfile.release
- scalastyle-config.xml
- scalastyle-test-config.xml
I initially thought that [mapAsync](https://doc.akka.io/api/akka/2.7/akka/stream/scaladsl/Source.html#mapAsync[T](parallelism:Int)(f:Out=%3Escala.concurrent.Future[T]):FlowOps.this.Repr[T]) was not preserving order, while it actually does. There is a specific [mapAsyncUnordered](https://doc.akka.io/api/akka/2.7/akka/stream/scaladsl/Source.html#mapAsyncUnordered[T](parallelism:Int)(f:Out=%3Escala.concurrent.Future[T]):FlowOps.this.Repr[T]) if you don't want to preserve.
This improved a lot the performance, 8 seems a good value while doing my test, going above didn't improved.
I added a config value so we can easily play with it if we want.
> Add parallelism to stream

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/BlockEndpoints.scala
- app/src/main/scala/org/alephium/explorer/api/QueryParams.scala
- app/src/main/scala/org/alephium/explorer/api/model/Pagination.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/service/BlockService.scala
- app/src/main/scala/org/alephium/explorer/service/IndexChecker.scala
- app/src/test/scala/org/alephium/explorer/Generators.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/service/EmptyBlockService.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/ListBlocksReadState.scala
Only one endpoint was actually using the `reverse` field, all others were ignoring it, which was confusing for users.
The idea here is to remove that reverse field and use it only when we explicitly want it.
Resolves: https://github.com/alephium/explorer-backend/issues/428
> Introduce `Pagination.Reversible`

- app/src/main/scala/org/alephium/explorer/persistence/queries/MempoolQueries.scala
- app/src/test/scala/org/alephium/explorer/Generators.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/MempoolQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/UInputQueriesSpec.scala
Currently we were only returning the txs going out an address. The wallet team thought it would be nice to also see when a tx is going toward an address.
We could remove the `DISTINCT` as `UNION` is removing duplicates.
Resolves: https://github.com/alephium/explorer-backend/issues/360
> Return mempool tx toward an address

- app/src/main/scala/org/alephium/explorer/ExplorerState.scala
- app/src/main/scala/org/alephium/explorer/Main.scala
We were previously having different boot up for `Read...` and `WriteOnly`, because the first ones needed an `ActorSystem`. Now that we use RxJava, we can unify everything.
> Clean `Main`

- app/src/main/resources/application.conf
- app/src/main/scala/org/alephium/explorer/service/HashrateService.scala
- app/src/test/scala/org/alephium/explorer/service/HashrateServiceSpec.scala
Related to: https://github.com/alephium/explorer-backend/issues/315
Hashrate are computed once on start. As hashrates are grouped by hourly/daily interval we can schedule the next hashrate computation on next round hour + a delay e.g if it's 08:20, next sync will occurs at 09:00 + syncDelay.
Currently we were re-scheduling every minutes to be sure we didn't miss the new round hour (aaaaargs)
> Compute hashrate only when necessary

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/BaseEndpoint.scala
- app/src/main/scala/org/alephium/explorer/api/Codecs.scala
- app/src/main/scala/org/alephium/explorer/api/EndpointExamples.scala
- app/src/main/scala/org/alephium/explorer/api/QueryParams.scala
- app/src/main/scala/org/alephium/explorer/api/Schemas.scala
- app/src/main/scala/org/alephium/explorer/api/TokensEndpoints.scala
- app/src/main/scala/org/alephium/explorer/api/model/FungibleTokenMetadata.scala
- app/src/main/scala/org/alephium/explorer/api/model/Input.scala
- app/src/main/scala/org/alephium/explorer/api/model/NFTCollectionMetadata.scala
- app/src/main/scala/org/alephium/explorer/api/model/NFTMetadata.scala
- app/src/main/scala/org/alephium/explorer/api/model/Output.scala
- app/src/main/scala/org/alephium/explorer/api/model/OutputRef.scala
- app/src/main/scala/org/alephium/explorer/api/model/StdInterfaceId.scala
- app/src/main/scala/org/alephium/explorer/api/model/Token.scala
- app/src/main/scala/org/alephium/explorer/api/model/TokenInfo.scala
- app/src/main/scala/org/alephium/explorer/api/model/Transaction.scala
- app/src/main/scala/org/alephium/explorer/docs/Documentation.scala
- app/src/main/scala/org/alephium/explorer/persistence/model/TokenInfoEntity.scala
Nothing change on scala side, the goal is to have better types when
generating the TS api on the FE side. Now we have a proper type when using the token interface id:
```
TokenStdInterfaceId | string
```
here are the generated TS: 
```typescript
export interface TokenInfo {
/** @Format 32-byte-hash */
token: string
/** Raw interface id, e.g. 0001 */
stdInterfaceId?: TokenStdInterfaceId | string
}
export enum TokenStdInterfaceId {
Fungible = 'fungible',
NonFungible = 'non-fungible',
NonStandard = 'non-standard'
}
```
also for the `interface-id` query param:
```typescript
/**
* fungible, non-fungible, non-standard or any interface id in hex-string format, e.g: 0001
* @Format string
*/
'interface-id'?: TokenStdInterfaceId | string
```
I also change some auto-gen schema to semi-derivated. …
> Std interface schema

- app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowClientSpec.scala
We were using a deprecated way of fetching nft metadata, we now follow what's inside our web3 package:
https://github.com/alephium/alephium-web3/blob/72ae2e0ef8c0274ffb3e0cedb33f609585b5757a/packages/web3/src/api/node-provider.ts#L136-L180
I tested it both in mainnet and testnet, everything seems fine. Of course on testnet we have some nft that are deprecated so we can't get their metadata, but that's expected.
@h0ngcha0 I put you as reviewer as you wrote the web3 part, you confirm that now `collectionId` and `index` are in the same `CallContractSucceeded`?
First elem is the collection_id and second is the index.
> Fix fetch of metadata

- .github/workflows/docker-buildx.yml
- .github/workflows/docker.yml
- .github/workflows/release.yml
- .github/workflows/scala.yml
See more:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> Update workflows to fix deprecation messages

- app/src/main/resources/application.conf
- app/src/main/scala/org/alephium/explorer/AppServer.scala
- app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala
- app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala
- app/src/main/scala/org/alephium/explorer/service/MarketService.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/main/scala/org/alephium/explorer/web/DocumentationServer.scala
- app/src/test/scala/org/alephium/explorer/ConfigDefaults.scala
- app/src/test/scala/org/alephium/explorer/service/MarketServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/DBBenchmark.scala
- tools/src/main/scala/org/alephium/tools/OpenApiUpdate.scala
From the front end, if you query for march 05 2023 to march 05 2024, then you have 366 days as it's a leap year. 
I think we can safely put 366 as default max value, one day won't change much and at least we are fine with leap years.
I added more config value so now every thing can be change from the config
cc @mvaivre
> Add more config for yearly data and default to 366 to handle leap years

- app/src/main/resources/application.conf
- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/ContractsEndpoints.scala
- app/src/main/scala/org/alephium/explorer/api/EndpointExamples.scala
- app/src/main/scala/org/alephium/explorer/api/model/ContractInfo.scala
- app/src/main/scala/org/alephium/explorer/api/model/ContractLiveness.scala
- app/src/main/scala/org/alephium/explorer/docs/Documentation.scala
- app/src/main/scala/org/alephium/explorer/persistence/model/ContractEntity.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/ContractQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala
- app/src/main/scala/org/alephium/explorer/web/ContractServer.scala
- app/src/test/scala/org/alephium/explorer/GenDBModel.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/ContractQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/web/ContractServerSpec.scala
Some examples:
```bash
curl -s 'http://localhost:9090/contracts/29VTmL2Hc9Uq2NnVQN8GeXiPFKr9guHeTTaL2ZzNDSaiB/info' | jq
[
{
"parent": "yAEfa2Aw495wcfb6up8wtnriStQ5VsGVh4xgJrZpnBbm",
"creationBlockHash": "000000000001b1b4dbce66c957b35f05812faab7226e1d3d98711cf89502a0f0",
"creationTxHash": "96858d80612d09dd25013491e9271f2b694717302fc6ef707a22be0fc8bbb273",
"creationTimestamp": 1709727660363,
"creationEventOrder": 6,
"destructionBlockHash": null,
"destructionTxHash": null,
"destructionTimestamp": null,
"destructionEventOrder": null,
"category": "0003",
"interfaceId": "non-fungible"
}
]
```
The second one we can see the contract was destroyed and recreated: 
```bash
curl -s 'http://localhost:9090/contracts/285FUvYcqmtx8WEJXa8sZPG9zRfyB7FockScnZcXDbHvo/info' | jq
[
{
"parent": …
```
> Contracts info endpoint

- app/src/main/scala/org/alephium/explorer/AppServer.scala
- app/src/main/scala/org/alephium/explorer/ExplorerState.scala
- app/src/main/scala/org/alephium/explorer/service/MarketService.scala
- app/src/test/scala/org/alephium/explorer/service/MarketServiceSpec.scala
This fix the shutdown of the explorer-backend, otherwise the sttp backend was not close and the explorer-backend was hanging infinitely when stopping.
> Convert MarketSevice into a start/stoppable service

- app/src/main/scala/org/alephium/explorer/Main.scala
- app/src/main/scala/org/alephium/explorer/WelcomeMessage.scala
- app/src/main/scala/org/alephium/explorer/config/BootMode.scala
The current info logs were not very clear if the explorer-backend was really started or not, so users were confused.
In this PR when the explorer-backend is successfully started, we then logs useful info. Here are the 3 possible cases based on the mode.
> Add Welcome message when explorer-backend is succesfully started

- app/src/main/resources/application.conf
- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/AppServer.scala
- app/src/main/scala/org/alephium/explorer/ExplorerState.scala
- app/src/main/scala/org/alephium/explorer/docs/Documentation.scala
- app/src/main/scala/org/alephium/explorer/web/DocumentationServer.scala
- tools/src/main/scala/org/alephium/tools/OpenApiUpdate.scala
Resolves #512
The generated TS types are then: 
```ts
export enum TokensWithPrice {
WETH = 'WETH',
ALPH = 'ALPH',
USDT = 'USDT',
AYIN = 'AYIN',
DAI = 'DAI',
USDC = 'USDC',
WBTC = 'WBTC'
}
export enum Currencies {
Btc = 'btc',
Usd = 'usd',
Eur = 'eur',
Chf = 'chf',
Gbp = 'gbp',
Idr = 'idr',
Vnd = 'vnd',
Rub = 'rub',
Try = 'try',
Cad = 'cad',
Aud = 'aud'
}
```
> Expose currencies and tokens with price in openapi

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/model/AmountHistory.scala
- app/src/main/scala/org/alephium/explorer/api/model/TimedAmount.scala
- app/src/main/scala/org/alephium/explorer/api/model/Transaction.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala
- build.sbt
Fixes: https://github.com/alephium/alephium-frontend/pull/680
the generated TS api is then: 
the data in array is actually `[ timestamp, string]`, but we can't represent such thing, so I checked with FE team and using string is all good.
> Amount history openapi

- app/src/main/scala/org/alephium/explorer/service/MarketService.scala
- app/src/main/scala/org/alephium/explorer/web/MarketServer.scala
- app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala
- app/src/test/scala/org/alephium/explorer/service/MarketServiceSpec.scala
This avoid returning a `5xx` when someone query an unknown symbol or currency
> Validate symbol and currency in market endpoints

- app/src/main/scala/org/alephium/explorer/Metrics.scala
- app/src/main/scala/org/alephium/explorer/api/MetricsEndpoints.scala
- app/src/main/scala/org/alephium/explorer/web/MetricsServer.scala
- build.sbt
- project/Dependencies.scala
Resolves: https://github.com/alephium/explorer-backend/issues/565
They are actually two different registries and `DefaultExports.initialize`
write to `CollectorRegistry` while tapir and HikariCP are writting to
`PrometheusRegistry`.
Only the second one was exposed through the metrics endpoint.
> Jvm metrics

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala
- app/src/main/scala/org/alephium/explorer/api/QueryParams.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/service/EmptyTransactionService.scala
`POST /addresses/transactions` was returning duplicate tx if multiple addresses of to the body share some common tx.
We also added `fromTs` and `toTs` optional query params to that endpoint to ease the pagination work.
> Improve post addresses transactions

- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
Now that we fixed the coinbase value and as we are querying for only 1 address, we will already receive a distinct set of transactions.
> Remove unnecessary `DISTINCT`

- app/src/main/scala/org/alephium/explorer/persistence/queries/ContractQueries.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/ContractQueriesSpec.scala
Fixes: https://github.com/alephium/explorer-backend/issues/560
In database we can have multiple entry for a same contract, if it was destroyed and recreated, that's why we had duplicated values
> Fix sub-contracts endpoint returning duplicate

- app/src/main/scala/org/alephium/explorer/cache/BlockCache.scala
- app/src/main/scala/org/alephium/explorer/persistence/DBInitializer.scala
- app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/OutputQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/InputSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/OutputSchema.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/OutputQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/service/EmptyTransactionService.scala
- app/src/test/scala/org/alephium/explorer/service/HolderServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/DBBenchmark.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala
The balance query was slow on addresses with a lot of unspent output.
Reducing the scope of the query with the address and the finalized timestamp + specific indexes improves a lot the query.
Here is some benchmarks, I made a lot of them but make a resume here
Example are done with some of our slowest addresses (extracted from the google cloud logs), they are in the top addresses in term of unspent output, around 150'000 of them. Queries were done on my local explorer backend. 
We have those various scenario:
1. Current state
2. With indexes
3. With indexes + new query
On the first query we see 1,2,3
On two next images, we see the query plan for 2 and 3 on two similar addresses
I was always shutting down pg and clearing caches to have a cold start.
We can see both new indexes being used …
> Improve balance query

- app/src/main/scala/org/alephium/explorer/cache/BlockCache.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
Instead of doing a count in PG, which is a very slow process, we rather rely on the `latest_blocks` table, we can just sum up all height of the latest inserted block.
> Improve caching of number of blocks

- app/src/main/scala/org/alephium/explorer/persistence/queries/TokenQueries.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TokenQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowClientSpec.scala
testnet is down due to this issue https://github.com/alephium/explorer-backend/issues/590
We retake the same quickfix as last time, but apply it everywhere, as implementing the above issue might take a bit more time
> Quifix for null byte char in string

- app/src/main/resources/application.conf
- app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala
- app/src/main/scala/org/alephium/explorer/error/ExplorerError.scala
- app/src/main/scala/org/alephium/explorer/persistence/model/AppState.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala
- app/src/main/scala/org/alephium/explorer/service/HashrateService.scala
- app/src/main/scala/org/alephium/explorer/service/MarketService.scala
- app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala
- app/src/test/scala/org/alephium/explorer/config/ExplorerConfigSpec.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowClientSpec.scala
- app/src/test/scala/org/alephium/explorer/service/MarketServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/util/ExecutionContextUtilSpec.scala
Regarding: Prevent `SttpBackend` to throw error on close
When stopping the `MarketService`, we have to close the `SttpBackend`
unfortunately we don't have much control over it and when it's closed
while doing a request, it's throwing an error and we were logging that
error.
It's correct in a way, but it was confusing on the reason why the
explorer-backend was stopping.
For example if the node stop while the market service is updating its
caches, an error was logged, saying the caches couldn't get updated.
This was confusing and let user think the market service was the reason
for the explorer-backend to stop.
We are now making sure that if we catch an error while the service is
stopped or not running, we don't throw the error.
On the other hand if the service is running, we do want to log …
> Various low hanging

- app/src/main/scala/org/alephium/explorer/cache/TransactionCache.scala
- app/src/main/scala/org/alephium/explorer/persistence/model/AppState.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala
- app/src/main/scala/org/alephium/explorer/service/FinalizerService.scala
- app/src/test/scala/org/alephium/explorer/cache/TestTransactionCache.scala
- app/src/test/scala/org/alephium/explorer/service/FinalizerServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
Previously in our `TransactionCache` every 10 minutes we were re-counting every txs in database, not optimal...
In this PR, we take advantage of the `FinalizerService`, which is grabbing every 10min every txs that needs to be finalized.
Here is the workflow:
* We keep in our `AppState` table the current count of finalized txs.
* When we finalize new txs, we add their count to the `finalized_tx_count` in `app_state`
* The `TransactionCache` is first reading the `finalized_tx_count` and only count txs that aren't finalized.
With this solution, whatever the number of transactions, the cache will only count a very small set of transactions.
> Optimize transaction cache

- app/src/main/scala/org/alephium/explorer/persistence/DBInitializer.scala
- app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala
- app/src/main/scala/org/alephium/explorer/persistence/model/MempoolTransactionEntity.scala
- app/src/main/scala/org/alephium/explorer/persistence/model/UInputEntity.scala
- app/src/main/scala/org/alephium/explorer/persistence/model/UOutputEntity.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/MempoolQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/CustomGetResult.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/InputSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/OutputSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TokenOutputSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TokenTxPerAddressSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TransactionPerAddressSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/UInputSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/UOutputSchema.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowClient.scala
- app/src/main/scala/org/alephium/explorer/util/AddressUtil.scala
- app/src/test/scala/org/alephium/explorer/GenDBModel.scala
- app/src/test/scala/org/alephium/explorer/persistence/dao/BlockDaoSpec.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala
A migration is needed to drop a index that has a wrong name + it was indexing the `address` field too while it only need `groupless_address`
> Add indexes for groupless address columns

- app/src/main/resources/application.conf
- app/src/main/scala/org/alephium/explorer/api/EndpointExamples.scala
- app/src/main/scala/org/alephium/explorer/api/model/Price.scala
- app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala
- app/src/main/scala/org/alephium/explorer/service/MarketService.scala
- app/src/test/scala/org/alephium/explorer/service/MarketServiceSpec.scala
- project/Dependencies.scala
We now try to fetch prices from both mobula and coingecko, in case one of them fail, we then merge the prices.
We are currently favoring mobula prices are the are more accurate, but since we lately had issue querying them, coingecko is here as a fallback.
> Bring back coingecko prices

- app/src/main/scala/org/alephium/explorer/persistence/Migrations.scala
In case we need to roll back the migration version, with this we can safely come back to a previous version
> Add a `IF EXISTS` safety in migration

- app/src/main/resources/application.conf
- app/src/main/scala/org/alephium/explorer/SyncServices.scala
- app/src/main/scala/org/alephium/explorer/config/ExplorerConfig.scala
- app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala
- app/src/test/scala/org/alephium/explorer/service/BlockFlowSyncServiceSpec.scala
We were previously considering that EB was synced if latest synced block was 10s ago ([defaultBackStep](https://github.com/alephium/explorer-backend/blob/f1ccc62169dee965e31e9d898239f2efc16d1726/app/src/main/scala/org/alephium/explorer/service/BlockFlowSyncService.scala#L53)), otherwise we were contacting the node to know the latest block's timestamp.
We are now using the `blockFlowFetchMaxAge` value, which is now part of the config and use the same value of 30min as set in the node.
If our latest block is younger than (now - blockFlowFetchMaxAge), we don't need to call the node as we anyway can sync all remaining blocks in one call.
The previous value of 10s was sometime not enough in case of heavy load, it could happen that EB was just 12 seconds late and we were thus calling the node …
> Optimize `BlockFlowSyncService.getRemoteMaxTimestamp`

- app/src/main/resources/application.conf
- app/src/main/scala/org/alephium/explorer/service/market/MarketService.scala
- app/src/test/scala/org/alephium/explorer/service/market/MarketServiceSpec.scala
- e2e/docker/docker-compose.yml
In our [token list](https://github.com/alephium/token-list/blob/684276e19d7ed7f05216b5ab4c509d25fe809720/tokens/mainnet.json#L126-L149) we have:
```
symbol = "USDCeth"
...
symbol = "USDCbsc" 
```
So when using the sdk, the FE is asking price for `USDCeth`, while we were currently only responding to `USDC` request.
This PR is handling such case.
Now we have:
> Support token price for multiple symbol with same token

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/AddressesEndpoints.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/MempoolQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TokenQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TokenTxPerAddressSchema.scala
- app/src/main/scala/org/alephium/explorer/persistence/schema/TransactionPerAddressSchema.scala
- app/src/main/scala/org/alephium/explorer/util/SlickUtil.scala
- app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala
- app/src/test/scala/org/alephium/explorer/GenApiModel.scala
- app/src/test/scala/org/alephium/explorer/GenCoreProtocol.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TokenQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/DBBenchmark.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/DataGenerator.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/AreAddressesActiveReadState.scala
Related to https://github.com/alephium/alephium-frontend/issues/1402
Few month ago we removed `DISTINCT` because they were less performant and not necessary, now following the above issue we need to bring them back for groupless addresses.
With this PR, the `DISTINCT` is added only if it's a groupless address, for regular one we keep the same query.
New indexes have been added  for those cases, I ran multiple benchmark, comparing the previous version and the new one.
I forced the requested data to be a half-decoded address, to be sure the `DISTINCT` were used.
The result are of course a bit slower, but negligible IMO, this is due to the indexes, before them the results were catastrophic.
```
[info] Benchmark                                  Mode  Cnt      Score   Error  Units
[info] …
```
> Unique txs groupless

- app/src/main/scala/org/alephium/explorer/AppServer.scala
- app/src/main/scala/org/alephium/explorer/ExplorerState.scala
- app/src/main/scala/org/alephium/explorer/cache/AddressTxCountCache.scala
- app/src/main/scala/org/alephium/explorer/persistence/dao/TransactionDao.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/main/scala/org/alephium/explorer/web/AddressServer.scala
- app/src/test/scala/org/alephium/explorer/cache/TestAddressTxCountCache.scala
- app/src/test/scala/org/alephium/explorer/service/EmptyTransactionService.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
- app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
- app/src/test/scala/org/alephium/explorer/web/StatementTimeoutSpec.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/DBBenchmark.scala
- benchmark/src/test/scala/org/alephium/explorer/benchmark/db/state/AddressReadState.scala
Previously, the address transaction count cache was optimized by updating the cached value "on-demand"—whenever a count was requested, the new value was written back to the database. However, this approach caused failures when running in `ReadOnly` mode, since database writes are not permitted.
This commit introduces separate cache implementations for read-only and write modes:
- **ReadOnly mode:** Uses an in-memory cache. Initial values are loaded from the database if available, but subsequent updates remain only in memory to avoid write operations.
- **Write mode:** Continues to use the database-backed cache, supporting persistent updates as before.
This change ensures correct and efficient behavior for both read-only and write-enabled instances.
> Fix Address Transaction Count Cache for `ReadOnly` Mode

- app/src/main/scala/org/alephium/explorer/persistence/queries/InputQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/OutputQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/result/InfoFromTxQR.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/result/InputFromTxQR.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/result/InputQR.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/result/OutputFromTxQR.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/result/OutputQR.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/InputQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/OutputQueriesSpec.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
There is a rare edge case when querying transactions that have just been inserted, but whose inputs have not yet been updated by `InputUpdateQueries`. In this scenario, the API returns the transactions, but the inputs are missing output data such as address and amount. This makes it difficult for applications to process these transactions.
To address this, the API should only return transactions with complete data. For this edge case (which typically lasts around 300ms between insert and update), when querying transactions, we check if input data is complete—which is almost always the case. If not, we retrieve the corresponding output so users always receive complete transaction data.
If for some reason we can't find the output, we'll return then incomplete input.
> Ensure transaction inputs return complete output data

- app/src/main/scala/org/alephium/explorer/persistence/dao/BlockDao.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/BlockQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/ContractQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/EventQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/InputQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TokenQueries.scala
- app/src/main/scala/org/alephium/explorer/persistence/queries/TransactionQueries.scala
- app/src/main/scala/org/alephium/explorer/service/TokenSupplyService.scala
- app/src/test/scala/org/alephium/explorer/GenDBModel.scala
- app/src/test/scala/org/alephium/explorer/persistence/queries/TransactionQueriesSpec.scala
We were using `SELECT *` in several queries and mapping the results directly to entity models. This approach is fragile and led to issues on testnet/mainnet.
For example, when we added the `conflicted` field to the transaction entity (positioned below `main_chain` in the model), a fresh database created the column in the expected order. However, in testnet/mainnet, where `conflicted` was added via migration, the column was placed at the end. As a result, `SELECT *` returned columns in the wrong order, causing `CustomGetResult` to misalign fields.
This commit replaces `SELECT *` with explicit column selection to ensure correct field mapping regardless of column order in the database schema.
This was also not catch by our test as some models where not creating all data (see first commit). …
> Fix incorrect field order in SQL queries due to use of SELECT *

- app/src/main/resources/explorer-backend-openapi.json
- app/src/main/scala/org/alephium/explorer/api/EndpointExamples.scala
- app/src/main/scala/org/alephium/explorer/api/TransactionEndpoints.scala
- app/src/main/scala/org/alephium/explorer/api/model/DecodeUnsignedTxResult.scala
- app/src/main/scala/org/alephium/explorer/api/model/UnsignedTransaction.scala
- app/src/main/scala/org/alephium/explorer/docs/Documentation.scala
- app/src/main/scala/org/alephium/explorer/service/TransactionService.scala
- app/src/main/scala/org/alephium/explorer/web/TransactionServer.scala
- app/src/test/scala/org/alephium/explorer/service/EmptyTransactionService.scala
- app/src/test/scala/org/alephium/explorer/service/TransactionServiceSpec.scala
Using the same format as the node, the only difference is that we can provide then input details.
Resolves https://github.com/alephium/explorer-backend/issues/642
> Add `/transactions/decode-unsigned-tx` endpoint with inputs details
